name: PR gate

on:
  pull_request:
    branches:
    - master

  # enable manual trigger
  workflow_dispatch:
    input:
      tags:
        description: 'Tags to label this manual run (optional)'
        default: 'Manual run'

jobs:
  test:
    name: Test Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        conda env list
        conda install "pyodbc>=4.0.21" "jupyter>=1.0.0" "pip>=19.2"
        pip install -r requirements.txt
        pip list

    - name: Python version
      run: |
        echo "Python: ${{ matrix.python }}"
        python --version

    - name: Run tests
      run: |
        pytest test/pytest* -m "not system"
